### ISSUE TITLE
Importar repositório para o NOW

### ISSUE THREAD

**Issue by SampaioLeal** [teresinahc/app-web-denuncia-aglomeracao-quarentena#6]
# Proposta
Criar uma conta no NOW e importar o repositório para que seja feito o deploy automático da aplicação para fins de testes e exposição da mesma.

**Link:** https://zeit.co/docs

**Comment by anapaulamendes** [comment]
Feito!

**Comment by SampaioLeal** [comment]
Coloca o link, de preferência o menor kkk, na descrição do repo ou no README
